"""
Turn model_int8.tflite into C source for the ESP32 firmware.

    python scripts/export_c_array.py

Writes models/model_data.cc and models/model_data.h, ready to drop into an
ESP-IDF component alongside esp-tflite-micro.

The 16-byte alignment on the array is required, not decorative. TFLite Micro
reads the flatbuffer in place from flash and will fail at GetModel() time on a
misaligned pointer.

This script is here so the handoff to firmware is one command rather than a
manual xxd and some hand-edited constants. Nothing in this stage of the project
needs it yet -- it is what Step 2 of the firmware plan will consume.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import config
from cropnet.labels import read_labels

BYTES_PER_LINE = 12


def to_identifier(name: str) -> str:
    """crop name -> C enum suffix, e.g. 'chilli pepper' -> 'CHILLI_PEPPER'."""
    cleaned = "".join(ch if ch.isalnum() else "_" for ch in name)
    return cleaned.upper().strip("_")


def format_array(data: bytes) -> str:
    lines = []
    for offset in range(0, len(data), BYTES_PER_LINE):
        chunk = data[offset:offset + BYTES_PER_LINE]
        lines.append("    " + " ".join(f"0x{b:02x}," for b in chunk))
    return "\n".join(lines)


def write_header(labels: list[str], size: int) -> None:
    enum_entries = "\n".join(
        f"    CROP_{to_identifier(label):<16} = {index},"
        for index, label in enumerate(labels)
    )

    header = f"""// Generated by scripts/export_c_array.py -- do not edit by hand.
//
// Model: {config.BACKBONE} alpha={config.ALPHA}, {config.IMAGE_SIZE}x{config.IMAGE_SIZE}x{config.IMAGE_CHANNELS}, int8 quantized.

#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

// The flatbuffer is read in place from flash, so the 16-byte alignment in the
// .cc file is required -- GetModel() fails on a misaligned pointer.
extern const unsigned char g_crop_model_data[];
extern const size_t g_crop_model_data_len;

#define CROP_MODEL_INPUT_WIDTH    {config.IMAGE_SIZE}
#define CROP_MODEL_INPUT_HEIGHT   {config.IMAGE_SIZE}
#define CROP_MODEL_INPUT_CHANNELS {config.IMAGE_CHANNELS}
#define CROP_MODEL_NUM_CLASSES    {len(labels)}

// Confidence below this means the Main ESP32 should keep its previous fan
// state rather than act on the detection.
#define CROP_CONFIDENCE_THRESHOLD {config.CONFIDENCE_THRESHOLD:.2f}f

// These values ARE the crop_id sent over ESP-NOW. The Main ESP32's fan-speed
// table is indexed by them, so they must never be reordered without changing
// that table to match.
typedef enum {{
{enum_entries}
    CROP_COUNT               = {len(labels)}
}} crop_id_t;

extern const char *const g_crop_labels[CROP_MODEL_NUM_CLASSES];

#ifdef __cplusplus
}}  // extern "C"
#endif
"""
    config.C_ARRAY_HEADER.write_text(header, encoding="utf-8")
    print(f"Wrote {config.C_ARRAY_HEADER}")


def write_source(data: bytes, labels: list[str]) -> None:
    label_entries = "\n".join(f'    "{label}",' for label in labels)

    source = f"""// Generated by scripts/export_c_array.py -- do not edit by hand.

#include "model_data.h"

// 16-byte alignment is required by TFLite Micro's in-place flatbuffer access.
#if defined(__has_attribute)
#if __has_attribute(aligned)
#define CROP_MODEL_ALIGN __attribute__((aligned(16)))
#endif
#endif
#ifndef CROP_MODEL_ALIGN
#define CROP_MODEL_ALIGN
#endif

const unsigned char g_crop_model_data[] CROP_MODEL_ALIGN = {{
{format_array(data)}
}};

const size_t g_crop_model_data_len = {len(data)};

const char *const g_crop_labels[CROP_MODEL_NUM_CLASSES] = {{
{label_entries}
}};
"""
    config.C_ARRAY_SOURCE.write_text(source, encoding="utf-8")
    print(f"Wrote {config.C_ARRAY_SOURCE}")


def main() -> None:
    if not config.TFLITE_MODEL.exists():
        raise SystemExit(
            f"Missing {config.TFLITE_MODEL}. Run scripts/export_tflite.py first."
        )

    data = config.TFLITE_MODEL.read_bytes()
    labels = read_labels(config.LABELS_FILE)

    write_header(labels, len(data))
    write_source(data, labels)

    # A C array of N bytes costs about 6N bytes of source text.
    print(f"\nModel: {len(data):,} bytes -> "
          f"{config.C_ARRAY_SOURCE.stat().st_size:,} bytes of C source")
    print("\nCrop IDs for the Main ESP32 fan-speed table:")
    for index, label in enumerate(labels):
        print(f"  {index:>2}  CROP_{to_identifier(label)}")


if __name__ == "__main__":
    main()
