// Generated by scripts/export_c_array.py -- do not edit by hand.
//
// Model: mobilenet_v1 alpha=0.5, 96x96x3, int8 quantized.

#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// The flatbuffer is read in place from flash, so the 16-byte alignment in the
// .cc file is required -- GetModel() fails on a misaligned pointer.
extern const unsigned char g_crop_model_data[];
extern const size_t g_crop_model_data_len;

#define CROP_MODEL_INPUT_WIDTH    96
#define CROP_MODEL_INPUT_HEIGHT   96
#define CROP_MODEL_INPUT_CHANNELS 3
#define CROP_MODEL_NUM_CLASSES    5

// Confidence below this means the Main ESP32 should keep its previous fan
// state rather than act on the detection.
#define CROP_CONFIDENCE_THRESHOLD 0.60f

// These values ARE the crop_id sent over ESP-NOW. The Main ESP32's fan-speed
// table is indexed by them, so they must never be reordered without changing
// that table to match.
typedef enum {
    CROP_BANANA           = 0,
    CROP_EMPTY            = 1,
    CROP_LEMON            = 2,
    CROP_ONION            = 3,
    CROP_TOMATO           = 4,
    CROP_COUNT               = 5
} crop_id_t;

extern const char *const g_crop_labels[CROP_MODEL_NUM_CLASSES];

#ifdef __cplusplus
}  // extern "C"
#endif
